//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Entities { 
public class AvailableApplications
{
	public virtual List<ApplicationDto> AllApps
	{
		get;
		set;
	}

	public virtual IEnumerable<ApplicationDto> ApplicationDto
	{
		get;
		set;
	}

	public virtual void getList()
	{
		throw new System.NotImplementedException();
	}

	public virtual void resync()
	{
		throw new System.NotImplementedException();
	}

	public virtual void addApplication(Application Application)
	{
		throw new System.NotImplementedException();
	}

    public virtual void addApplication(ApplicationDto applicationDto)
    {
        throw new System.NotImplementedException();
    }

}
}
