//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Entities { 
    public class AvailableNetworks
    {
	    public virtual List<Network> Networks
	    {
		    get;
		    set;
	    }

	    public virtual IEnumerable<Network> Network
	    {
		    get;
		    set;
	    }

	    public virtual List<Network> get()
	    {
		    throw new System.NotImplementedException();
	    }

    }
}
