//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class AvailableDevices
{
	public virtual List<BluetoothDevice> Devices
    {
		get;
		set;
	}

	public virtual IEnumerable<BluetoothDevice> BluetoothDevice
	{
		get;
		set;
	}

	public virtual List<BluetoothDevice> get()
	{
		throw new System.NotImplementedException();
	}

}

