//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class BrowserTab
{
	public virtual string CurrentUrl
	{
		get;
		set;
	}

	public virtual string SessionId
	{
		get;
		set;
	}

	public virtual void goBack()
	{
		throw new System.NotImplementedException();
	}

	public virtual void goForward()
	{
		throw new System.NotImplementedException();
	}

	public virtual void goToUrl(string Url)
	{
		throw new System.NotImplementedException();
	}

	public virtual void reload()
	{
		throw new System.NotImplementedException();
	}

}

