//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Entities
{
    public class RunningApplications
    {
        public virtual List<Application> RunningApplication
        {
            get;
            set;
        }

        public virtual IEnumerable<Application> Application
        {
            get;
            set;
        }

        public virtual void findUnresponsive()
        {
            throw new System.NotImplementedException();
        }

        public virtual void showRunningApps()
        {
            throw new System.NotImplementedException();
        }

    }


}
