//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ApplicationService
{
	public virtual List<Application> Applications
	{
		get;
		set;
	}

	public virtual Application LaunchApplication()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool CloseApplication(Application app)
	{
		throw new System.NotImplementedException();
	}

}

