//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class BluetoothDevice
{
	public virtual string Name
	{
		get;
		set;
	}

	public virtual string Address
	{
		get;
		set;
	}

	public virtual boolean Paired
	{
		get;
		set;
	}

	public virtual PairingMode Mode
	{
		get;
		set;
	}

	public virtual void Pair()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Forget()
	{
		throw new System.NotImplementedException();
	}

	public virtual void EnablePairing()
	{
		throw new System.NotImplementedException();
	}

}

