//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class BluetoothViewModel
{
	public virtual BluetoothService BluetoothService
	{
		get;
		set;
	}

	public virtual List<BluetoothDevices> PairedDevices
	{
		get;
		set;
	}

	public virtual List<BluetoothDevices> AvailableDevices
	{
		get;
		set;
	}

	public virtual void PairDeviceCommand()
	{
		throw new System.NotImplementedException();
	}

	public virtual void ListPairedDevicesCommand()
	{
		throw new System.NotImplementedException();
	}

	public virtual void ForgetDeviceCommand()
	{
		throw new System.NotImplementedException();
	}

	public virtual void ListAvailableDevicesCommand()
	{
		throw new System.NotImplementedException();
	}

	public virtual void TogglePairingModeCommand(object boolean toggle)
	{
		throw new System.NotImplementedException();
	}

	public virtual void SearchForDevicesCommand()
	{
		throw new System.NotImplementedException();
	}

}

