//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class BluetoothService
{
	public virtual List<BluetoothDevice> SearchForDevices()
	{
		throw new System.NotImplementedException();
	}

	public virtual void PairDevice(string name)
	{
		throw new System.NotImplementedException();
	}

	public virtual void ForgetDevice(string name)
	{
		throw new System.NotImplementedException();
	}

	public virtual void EnablePairingMode(BluetoothDevice device)
	{
		throw new System.NotImplementedException();
	}

}

