//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Browser : Application
{
	public virtual BrowserType BrowserType
	{
		get;
		set;
	}

	public virtual List<BrowserWindow> ActiveWindows
	{
		get;
		set;
	}

	public virtual void OpenWindow()
	{
		throw new System.NotImplementedException();
	}

	public virtual void CloseWindow()
	{
		throw new System.NotImplementedException();
	}

	public virtual void GetHistory(DateTime dateRange)
	{
		throw new System.NotImplementedException();
	}

	public virtual void CloseTab()
	{
		throw new System.NotImplementedException();
	}

}

