//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class BrowserWindow
{
	public virtual List<BrowserTab> Tabs
	{
		get;
		set;
	}

	public virtual string ProcessId
	{
		get;
		set;
	}

	public virtual void Close()
	{
		throw new System.NotImplementedException();
	}

	public virtual void NewTab()
	{
		throw new System.NotImplementedException();
	}

	public virtual void CloseTab()
	{
		throw new System.NotImplementedException();
	}

}

