//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class BrowserService : ApplicationService
{
	public virtual List<Browser> OpenBrowsers
	{
		get;
		set;
	}

	public virtual void OpenNewWindow(Browser browser)
	{
		throw new System.NotImplementedException();
	}

	public virtual void OpenNewTab(BrowserWindow window)
	{
		throw new System.NotImplementedException();
	}

	public virtual void CloseTab()
	{
		throw new System.NotImplementedException();
	}

	public virtual void CloseWindow(BrowserWindow window)
	{
		throw new System.NotImplementedException();
	}

	public virtual void ReloadPage(BrowserTab tab)
	{
		throw new System.NotImplementedException();
	}

	public virtual void PreviousePage(BrowserTab tab)
	{
		throw new System.NotImplementedException();
	}

	public virtual void GetBrowserHistory(Browser browser)
	{
		throw new System.NotImplementedException();
	}

}

