//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class BrowserViewModel : ApplicationViewModel
{
	public virtual BrowserService BrowserService
	{
		get;
		set;
	}

	public virtual void NewWindowCommand()
	{
		throw new System.NotImplementedException();
	}

	public virtual void NewTabCommand()
	{
		throw new System.NotImplementedException();
	}

	public virtual void ReloadCommand()
	{
		throw new System.NotImplementedException();
	}

	public virtual void CloseTabCommand()
	{
		throw new System.NotImplementedException();
	}

	public virtual void CloseWindowCommand()
	{
		throw new System.NotImplementedException();
	}

	public virtual void GetBrowserHistoryCommand()
	{
		throw new System.NotImplementedException();
	}

	public virtual void PreviousPageCommand()
	{
		throw new System.NotImplementedException();
	}

}

