//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ComputerSettingsViewModel
{
	public virtual ComputerSettingsService ComputerSettingsService
	{
		get;
		set;
	}

	public virtual void ViewNetworkStatsCommand()
	{
		throw new System.NotImplementedException();
	}

	public virtual void ViewCPUUtilizationCommand()
	{
		throw new System.NotImplementedException();
	}

	public virtual void ViewRAMUsageCommand()
	{
		throw new System.NotImplementedException();
	}

}

