//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ComputerStatsService
{
	public virtual List<SystemStatistic> SystemStatistics
	{
		get;
		set;
	}

	public virtual string GetStat(SystemStatistic stat)
	{
		throw new System.NotImplementedException();
	}

}

