//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class DisplayViewModel
{
	public virtual List<Monitor> ConnectedMonitors
	{
		get;
		set;
	}

	public virtual DisplayMonitorService DisplayMonitorService
	{
		get;
		set;
	}

	public virtual void AdjustBrigtnessCommand()
	{
		throw new System.NotImplementedException();
	}

	public virtual void AdjustContrastCommand()
	{
		throw new System.NotImplementedException();
	}

	public virtual void TurnOffMonitorCommand()
	{
		throw new System.NotImplementedException();
	}

	public virtual void AdjustHueCommand()
	{
		throw new System.NotImplementedException();
	}

}

