//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class DisplayMonitorService
{
	public virtual void AdjustBrightness(int level, Monitor monitor)
	{
		throw new System.NotImplementedException();
	}

	public virtual void AdjustContrast(int level, Monitor monitor)
	{
		throw new System.NotImplementedException();
	}

	public virtual void AdjustHue(int level, monitor monitor)
	{
		throw new System.NotImplementedException();
	}

}

