//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class NetworkService
{
	public virtual Network ConnectToNetwork()
	{
		throw new System.NotImplementedException();
	}

	public virtual List<Network> SearchForAvailableNetworks()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool DisconnectFromNetwork(Network network)
	{
		throw new System.NotImplementedException();
	}

}

