//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <remarks>e.g., WiFi, DSL, T3, Cable, etc.</remarks>
public enum NetworkType
{
	WIFI,
	LAN,
	DSL,
	FIBER,
}
