//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class NetworkViewModel
{
	public virtual NetworkService NetworkService
	{
		get;
		set;
	}

	public virtual List<Network> AvailableNetworks
	{
		get;
		set;
	}

	public virtual Network CurrentNetwork
	{
		get;
		set;
	}

	public virtual void ConnectToNetworkCommand()
	{
		throw new System.NotImplementedException();
	}

	public virtual void ViewAvailableNetworksCommand()
	{
		throw new System.NotImplementedException();
	}

	public virtual void DisconnectFromNetworkCommand()
	{
		throw new System.NotImplementedException();
	}

}

