//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <remarks>
/// Componet and Statistic Example:
/// 
/// Memory is a component
/// "In Use," "Committted," and "Paged pool" are examples of Memory statistics.
/// 
/// Disk is a component
/// "Active Time," "Average Response Time" and "Read speed" are examples of Disk statistics.
/// 
/// </remarks>
public class SystemComponent
{
	public virtual string ComponentName
	{
		get;
		set;
	}

	public virtual List<SystemStatistic> Statistics
	{
		get;
		set;
	}

	public virtual Statistics GetStatistics()
	{
		throw new System.NotImplementedException();
	}

}

