//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Application
{
	public virtual string Name
	{
		get;
		set;
	}

	public virtual long ProcessId
	{
		get;
		set;
	}

	public virtual string Filepath
	{
		get;
		set;
	}

	public virtual void open()
	{
		throw new System.NotImplementedException();
	}

	public virtual void close()
	{
		throw new System.NotImplementedException();
	}

}

