//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <remarks>e.g., Chrome, Firefox, IE, etc.</remarks>
public class BrowserType
{
	public virtual string Name
	{
		get;
		set;
	}

	public virtual bool DefaultBrowser
	{
		get;
		set;
	}

	public virtual bool isDefault()
	{
		throw new System.NotImplementedException();
	}

	public virtual string getName()
	{
		throw new System.NotImplementedException();
	}

}

