//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Browser
{
	public virtual BrowserType BrowserType
	{
		get;
		set;
	}

	public virtual List<BrowserWindow> ActiveWindows
	{
		get;
		set;
	}

	public virtual void openNewWindow()
	{
		throw new System.NotImplementedException();
	}

	public virtual void closeWindow()
	{
		throw new System.NotImplementedException();
	}

	public virtual void getHistory(DateTime dateRange)
	{
		throw new System.NotImplementedException();
	}

}

