//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Monitors
{
	//public virtual List<Monitor> Monitor
	//{
	//	get;
	//	set;
	//}

	public virtual IEnumerable<Monitor> Monitor
	{
		get;
		set;
	}

	public virtual Monitor getMonitor(long MonitorId)
	{
		throw new System.NotImplementedException();
	}

}

